image: registry.dev-internal.crmstyle.com/synergy/futuredev/images/docker-openjdk:8

stages:
  - build

pages:
  stage: build
  image: node:13.7-alpine
  before_script:
    - npm install -g redoc-cli
  script:
    - redoc-cli bundle ./dep/swagger.yml
    - mkdir .public
    - cp -r ./redoc-static.html .public
    - mv .public public
  artifacts:
    paths:
      - public

publish:
  stage: build
  before_script:
    - git remote add github https://github.com/marumoto-ryusuke/test_doc.git
    - git config --global user.email hfg.archer@gmail.com
    - git config --global user.name marumoto.ryusuke
  script:
    - git push github master
